### ISSUE TITLE
Where can I find the `debouncing` crate?

### ISSUE THREAD

**Issue by theotherjimmy** [TyberiusPrime/stm32f103_k2k#1]
You reference a crate, `debouncing`, by path in your `Cargo.toml` that I can't seem to find in your github. Where can I find this crate?

```toml
[dependencies.debouncing]
path = "../debouncing"
```
